# Generated by Django 2.1.1 on 2018-09-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='image_default.jpg', upload_to='profile_pics'),
        ),
    ]
