# Generated by Django 2.1.1 on 2018-09-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=350)),
                ('message', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='mysite_img')),
            ],
        ),
    ]
