# Generated by Django 2.1.1 on 2018-09-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='info',
            name='title',
            field=models.CharField(max_length=350),
        ),
    ]
