# Generated by Django 2.1.1 on 2018-09-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='noimage.jpg', upload_to='blog_img'),
        ),
    ]
