# Generated by Django 2.1.1 on 2018-09-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180929_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='no_image.jpg', upload_to='blog_img'),
        ),
    ]
