# Generated by Django 2.1.1 on 2018-09-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='no_image.jpg', upload_to='blog_img'),
        ),
    ]
